"""
This is a setup.py script generated by py2applet
Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['jobhuntpy.py']

setup(
    app=APP,
    install_requires=['argparse', 'nose', 'requests'],
    author="Winston Chen",
    author_email="darwing.chen@gmail.com",
    license='MIT',
    entry_points={
        'console_scripts': [
            'jobhuntpy=jobhuntpy:main',
        ],
    },
)