"""
This is a setup.py script generated by py2applet
Usage:
    python setup.py py2app
"""

from distutils.core import setup

setup(
    name='jobhuntpy',
    version='0.0.1',
    author='',
    author_email='',
    packages=['jobhuntpy'],
    scripts=[],
    url='https://github.com/wingchen/jobhuntpy',
    install_requires=['argparse', 'nose', 'requests', 'beautifulsoup4'],
    license='MIT',
    entry_points={
        'console_scripts': [
            'jobhuntpy=jobhuntpy.jobhuntpy:main',
        ],
    },
)